### ISSUE TITLE
怎么联系微信你们啊？

### ISSUE THREAD

**Issue by Tyxiaomi** [weixin/WeIndex#2]
我在做一个用canvas画图的小程序，但我在画时，页面总是跟着上下动，怎么解决呢，catchtouchmove,并不能阻止页面的上拖，下拽。fixed也不保持页面相对屏幕不动。scroll-view在内部元素不能再上下拖动时也会使整个页面上下拖拽。
在iphone6真机上测试的，开发者工具内是没问题的，要能在真机上测试通过的方法。。。。搞个微信群啊，微信的大神。。

**Comment by hzlzh** [comment]
如果有 WXSS 相关的问题，建议去 https://github.com/weui/weui-wxss 看看，页面上有讨论的地方，和 repo 不相关的问题，不要在 Github 上发问。
