### ISSUE TITLE
关于微信公众号平台的编辑器

### ISSUE THREAD

**Issue by lichinlichin** [weixin/WeIndex#4]
您好，请问我可以使用
>微信公众平台网站
   >素材管理中
      编辑器的
      UI风格和图片
做项目吗？
很喜欢你们的编辑器样式

![image](https://cloud.githubusercontent.com/assets/13887816/22737039/47a2d046-ee3c-11e6-9d67-790cd3b3eaa5.png)

**Comment by hzlzh** [comment]
可以的，个人非商用就没有问题
