### ISSUE TITLE
问一下多客服接口报65400咋破

### ISSUE THREAD

**Issue by feifanyajun** [weixin/WeIndex#9]
官网提供的公众平台测试账号系统
https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login

添加客服。。。
微信请求发生错误！错误代码：65400，说明：please enable new custom service, or wait for a while if you have enabled hint: [5t8UwA02431551]

**Comment by hzlzh** [comment]
请在微信开发者后台询问
